"""Per-interior exposure trim from review shots (plain python): mean linear luminance of shots/int_<id>_<tag>.jpg (centre 80 %,
the top 2 % of pixels clipped so a lamp or a window doesn't decide it) -> factor toward TARGET, multiplied into the previous table.
Writes src/world/interiors/hero_int_expo.js. usage: python tools/blender/int_expo.py [tag=v2] [--reset]"""
import glob, os, re, sys, json
import numpy as np
from PIL import Image
ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
OUT = os.path.join(ROOT, 'src', 'world', 'interiors', 'hero_int_expo.js')
TARGET = 0.26                     # linear mean (about sRGB 0.55): a bright, lit interior, but no white-out
tag = next((a for a in sys.argv[1:] if not a.startswith('--')), 'v2')
old = {}
if os.path.exists(OUT) and '--reset' not in sys.argv:
    m = re.search(r'HERO_INT_EXPO = (\{.*\});', open(OUT).read(), re.S)
    if m: old = json.loads(m.group(1))
out = dict(old)
for f in sorted(glob.glob(os.path.join(ROOT, 'shots', 'int_*_%s.jpg' % tag))):
    bid = os.path.basename(f)[4:-(len(tag) + 5)]
    if bid == 'sheet': continue
    a = np.asarray(Image.open(f).convert('RGB'), np.float32) / 255.0
    h, w = a.shape[:2]; a = a[int(h * 0.1):int(h * 0.9), int(w * 0.1):int(w * 0.9)]
    lin = np.where(a <= 0.04045, a / 12.92, ((a + 0.055) / 1.055) ** 2.4)
    l = (lin @ np.array([0.2126, 0.7152, 0.0722], np.float32)).ravel()
    l = np.minimum(l, np.percentile(l, 98))
    k = float(np.clip(TARGET / max(l.mean(), 1e-3), 0.45, 2.2)) ** 0.75
    out[bid] = round(old.get(bid, 1.0) * k, 3)
    print(bid, round(float(l.mean()), 3), out[bid])
open(OUT, 'w').write('// GENERATED by tools/blender/int_expo.py from review shots: per-interior lightmap exposure trim (hero_int.js).\n'
                     'export const HERO_INT_EXPO = ' + json.dumps(out, sort_keys=True) + ';\n')
